const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const NEW_GAME = "GAME_NEW";
const DRAW = "DRAW";
const MOVE = "GAME_MOVE";
const CHANGE_PLAYER = "CHANGE_PLAYER";
const WINNER = "GAME_WINNER";
const TIMER_TIC = "TIMER_TIC";
const GAME_OVER = "GAME_OVER";

export {
  INCREMENT,
  DECREMENT,
  NEW_GAME,
  DRAW,
  MOVE,
  CHANGE_PLAYER,
  WINNER,
  TIMER_TIC,
  GAME_OVER
};
